### ISSUE TITLE
Feature request: Support current django versions

### ISSUE THREAD

**Issue by unicode-it** [kleingeist/django-tiles-gl#2]
Is this project still maintained? What hinders Django version >=4.2 to be supported?

**Comment by kleingeist** [comment]
@unicode-it its not in active use by me at the moment, thus i did not update it in a while

just tested and bumped up the supported django versions to <6 and released [Release v0.3.9](https://github.com/kleingeist/django-tiles-gl/releases/tag/v0.3.9)

it is released to PyPI now and you should be able to upgrade your dependency https://pypi.org/project/django-tiles-gl/0.3.9/
